services:
  db:
    container_name: sm_kiosk_db_container
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d
